### ISSUE TITLE
Set up Kanban board issue

### ISSUE THREAD

**Issue by HERMON-1995** [HERMON-1995/My-movies-capstone-project#21]
**For this project, we are a group of 2.**
Project link: [Link](https://github.com/HERMON-1995/Module-2-capstone-project/projects/1)

**Comment by Mihndim2020** [comment]
### Hi Team, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good with issue summary

There are some issues that you still need to work on to get this project approved, but you are almost there!
![ALMOST-MINION](https://user-images.githubusercontent.com/65852621/133680327-431cb21d-ad7c-483a-84eb-21b733980a04.png)

# Status: Requires Changes ♻️
_Check the comments under the review._

- [ ] Please make sure you update the link to your `kanban board` to 👉 [this](https://github.com/HERMON-1995/Module-2-capstone-project/projects/1), so that it takes you directly to the `Kanban Board`. 
- [ ] Make sure all cards are assigned to team members. There should be a circle with the user's avatar on each card. All cards with `group task` in the title should be assigned to someone.  See the image below

![task_assignment](https://user-images.githubusercontent.com/65852621/224666106-3fcdc6c1-1d8b-4728-a133-d05db09d89f4.PNG)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by HERMON-1995** [comment]
Thanks for the review but we want to know what you mean when you say "Please make sure you update the link to your kanban board" @Mihndim2020.

**Comment by DuaneDave** [comment]
Hi @preciousbetine and @HERMON-1995 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ Good set up of the kanban


 ## Required Changes ♻️
- The link to the kanban board is still not working as the previous reviewer pointed out. Kindly fix this to make it easy to access the board. in order to fix this, copy this exact setup below.

[Link](the url to the board should be pasted in here)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by omar-muhamad** [comment]
# Approved ✔
### Hi @HERMON-1995 and @preciousbetine 

#### Great job, Your project is complete!  There is nothing else to say other than... it's time to close this issue and start working on the project :shipit: 

### GOOD LUCK 🤞 

![giphy (1)](https://user-images.githubusercontent.com/68796232/223283296-e4ee61b3-5609-4707-a1c7-5a3da02d5db9.gif)

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
